# Generated by Django 4.1.5 on 2023-04-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="test_field",
            field=models.CharField(max_length=3),
        ),
    ]
